### PR TITLE
Make it more OpenShift secrets friendly

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Usage:

```
docker run -t -e DYNAMODB_CLIENT_CREDENTIALS_CLASS_NAME=com.amazonaws.auth.DefaultAWSCredentialsProviderChain -e DYNAMODB_PREFIX=me -e AWS_ACCESS_KEY_ID=key -e AWS_SECRET_ACCESS_KEY=key  registry.centos.org/datamodel/gremlin:concaf
```

**Comment by tuxdna** [comment]
@msrb: You many want to add the `docker` command to a README as well.

LGTM.

**Comment by msrb** [comment]
@tuxdna yeah, I fully agree with you that having README would be useful. In any case, since build in centos pipeline could take some time, could we merge this now - to kick off the build, and add the README later?

**Comment by tuxdna** [comment]
@msrb Merged.

**Comment by msrb** [comment]
Thanks Saleem ;)

**Pull request merged**
