### PR TITLE
Add an entrypoint to connect to local instance of DynamoDB

### PR DESCRIPTION
**Pull request by tuxdna**
Fixes issue - https://github.com/containscafeine/data-model/issues/23

### CODE REVIEW

**Comment by tuxdna** [comment]
@miteshvp @containscafeine @msrb Please review and merge

**Comment by tuxdna** [comment]
@miteshvp @containscafeine @msrb ping

**Comment by concaf** [comment]
@tuxdna just took a brief look at it, and looks good, but I didn't try it out.
Maybe @msrb @miteshvp can help with testing this.

**Comment by tuxdna** [comment]
@msrb @miteshvp Ping

**Comment by miteshvp** [comment]
LGTM !!

**Pull request merged**
