### PR TITLE
Added Thread Pool as COnfiguration Options

### PR DESCRIPTION
**Pull request by miteshvp**

### CODE REVIEW

**Comment by tuxdna** [comment]
What does this change do?

**Comment by miteshvp** [comment]
You can configure thread pool options with this config change

**Comment by tuxdna** [comment]
Doesn't seem like it is configurable at all, as the values are hard-coded in the script.

**Comment by miteshvp** [comment]
Thanks @tuxdna, overlooked that part. Changed now.

**Comment by tuxdna** [comment]
@miteshvp LGTM. I don't have write access so you may have to merge yourselves.

**Pull request merged**
